const attractionsData = [
   {
      _id: 1,
      Id: 5041,
      Name: 'גן לאומי בית גוברין',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: דרום, כתובת: גן לאומי בית גוברין',
      FullDescription:
         '<p style="text-align: right;">בגן הלאומי בית גוברין תוכלו לראות בין היתר אמפיתיאטרון רומי, לטפס לראשו של תל מרשה ולהשקיף ממנו אל הנוף עוצר הנשימה המשתרע עד לים התיכון. בגן יש מערות רבות שראשיתן כמחצבות שפעלו לפני כ-2,300 שנה. תוכלו לבקר במערת הקולומבריום (מערת היונים), במערת בית הבד ובמערות הקבורה הצידוניות – המערה "הצידונית" ו"קבר המוסיקאים" -  המעוטרות בציורי קיר צבעוניים בסגנון יווני. במערת הפעמון המרשימה, המשמשת אכסניה לקונצרטים ולאירועים אחרים, ניכרים עדיין הסימנים שהותירוהחוצבים שחדרו את פני הקרקע דרך חור קטן.</p>\n<p style="text-align: right;">קרדיט לתמונה: מני שמעוני</p>\n<p style="text-align: right;">שימו לב!<br />בעקבות משבר הקורונה קיימת הגבלה של מספר המבקרים באתרי רט"ג ונדרש רישום מראש. <a href="https://www.parks.org.il/%D7%94%D7%96%D7%9E%D7%A0%D7%95%D7%AA-%D7%9C%D7%90%D7%AA%D7%A8%D7%99%D7%9D/#1" target="_blank">לינק להרשמה</a>.</p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/הגן-הלאומי-בית-גוברין',
      Accessibility: 'כן',
      Address: 'גן לאומי בית גוברין',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00,  שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: '<a href="tel:+972-8-6811020">+972-8-6811020</a>',
      Region: 'דרום',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2HgSpdO',
      X: 34.895464,
      Y: 31.601631,
   },
   {
      _id: 2,
      Id: 5042,
      Name: 'הגן הלאומי תל דן',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אתרים לאומיים, אזור: צפון, כתובת: ליד קיבוץ דן',
      FullDescription:
         '<p style="text-align: right;">הגן הלאומי תל דן משלב בתוכו שמורת טבע שופעת מים וירק ואתר ארכיאולוגי מקראי.</p>\n<p style="text-align: right;">אפשר לסייר בפארק בשלושה מסלולי הליכה נוחים ובמסלול קצר נגיש לכיסאות גלגלים.</p>\n<p style="text-align: right;">במרכזו של הפארק נמצא תל דן, בירת הממלכה הצפונית הקדומה, שם תוכלו לראות את השער המפואר של העיר הכנענית ליש ושפע של ממצאים אחרים.</p>\n<p style="text-align: right;">בשמורה זורם נחל דן שהוא אחד ממקורות הירדן, והוא הניזון ממי השלגים המפשירים על החרמון הנמצא בסמוך.</p>\n<p style="text-align: right;">ברכת השכשוך מזמינה את המטיילים לטבילה מרעננת.</p>\n<p style="text-align: right;">הכביש אל הפארק יורד מכביש 99 צפונית לקרית שמונה.</p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/הגן-הלאומי-תל-דן',
      Accessibility: 'כן',
      Address: 'ליד קיבוץ דן',
      Attraction_Type: 'אתרים לאומיים;פארקים וגנים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: ' <a href="mailto:\tmoked@npa.org.il"> \tmoked@npa.org.il </a> ',
      Notes: '',
      Notes_for_opening_hours:
         'ערב ראש השנה, ערב יום כיפור, ערב פסח: 08:00 - 13:00',
      Opening_Hours:
         'שעון קיץ:</br> יום ראשון: 08:00 - 17:00,  יום שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערבי חג: 08:00 - 16:00 </br> שעון חורף: </br> יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערבי חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-4-6951579">+972-4-6951579</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2EBURbF',
      X: 35.651235,
      Y: 33.24757,
   },
   {
      _id: 3,
      Id: 5045,
      Name: 'גן לאומי תל מגידו',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: צפון, כתובת: גן לאומי תל מגידו',
      FullDescription:
         '<p style="text-align: right;">תל מגידו, הוא תל ארכאולוגי חשוב מתקופת המקרא, הנמצא בסמוך לצומת דרכים שהיה חשוב בעולם העתיק ועודנו חשוב גם בימינו.</p>\n<p style="text-align: right;">הכללתו של תל מגידו ברשימת אתרי המורשת העולמית של ארגון אונסקו מעידה על חשיבותו הרבה של התל.</p>\n<p style="text-align: right;">באלף השלישי לפני הספירה הייתה מגידו עיר מבוצרת היטב; כעבור 1,000 שנה היא הייתה למרכז השלטון המצרי והיא נזכרת בתנ"ך כ-20 פעם.</p>\n<p style="text-align: right;">בנצרות מזהים אותה עם ארמגדון של חזון אחרית הימים. מומלץ מאוד לבקר ב\'שער שלמה\'; להתבשם מנופי עמק יזרעאל הפסטורליים ולהתרשם ממערכת המים התת-קרקעית מהמאה ה-9 לפנה"ס – המעידה על היכולות המרשימות ועל היוזמה של מקימיה.</p>\n<p style="text-align: right;">קרדיט לתמונה: אבישי טייכר. מתוך אתר פיקיוויקי.</p>\n<p style="text-align: right;"> </p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/הגן-הלאומי-מגידו',
      Accessibility: 'כן',
      Address: 'גן לאומי תל מגידו',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: ' <a href="mailto:gl.megido@npa.org.il\t"> gl.megido@npa.org.il\t </a> ',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00,  שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-4-6590316">+972-4-6590316</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2XFBojc',
      X: 35.184692,
      Y: 32.585379,
   },
   {
      _id: 4,
      Id: 5321,
      Name: 'חוף פרישמן',
      ShortDescription:
         'סוג אטרקציה: חופים, אזור: תל אביב והמרכז, כתובת: רציף הרברט סמואל/פרישמן, תל אביב-יפו',
      FullDescription:
         '<p style="text-align: right;">פרישמן הוא חוף מוכרז הנקרא על שם הרחוב שמוביל אליו.</p>\n<p style="text-align: right;">בגבו נמצאים בתי מלון, בהם מלון דן שמוכר כבניין הצבעוני, כמו גם מסעדות ומועדונים.</p>\n<p style="text-align: right;">גם בחוף אפשר לנשנש ארוחה קלה ובירה במסעדות החוף ובמזנון.</p>\n<p style="text-align: right;">המשתזפים יכולים לשכור בחוף כסאות נוח ושמשיות, הילדים יכולים לשחק במתקני השעשועים וחובבי הספורט יכולים לשחק כדורעף במשטח חולי המיועד לכך ובמרכזו הרשת.</p>\n<p style="text-align: right;">צלם: משפחת ענתבי.מתוך אתר פיקיוויקי.</p>\n<p style="text-align: right;"> </p>',
      VendorId: 34,
      Vendor_Name: 'עיריית תל אביב יפו',
      Product_Url: 'https://info.goisrael.com/he/חוף-פרישמן-5321',
      Accessibility: 'כן',
      Address: 'רציף הרברט סמואל/פרישמן, תל אביב-יפו',
      Attraction_Type: 'חופים',
      Blue_Flag: 'כן',
      City: 'תל אביב יפו',
      Diving_beach: 'לא',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'בתשלום',
      Phone: '<a href="tel:+9723-7240190">+9723-7240190</a>',
      Region: 'תל אביב והמרכז',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: 'לא',
      URL: 'https://www.tel-aviv.gov.il/Visitors/Beaches/Pages/Frishman.aspx',
      X: 34.7689713,
      Y: 32.080027,
   },
   {
      _id: 5,
      Id: 5326,
      Name: 'חוף תל ברוך',
      ShortDescription:
         'סוג אטרקציה: חופים, אזור: תל אביב והמרכז, כתובת: יצחק ארצי, תל אביב-יפו',
      FullDescription:
         '<p style="text-align: right;">החוף ממוקם בסמוך לחוף הצוק, לרמת אביב ולשדה התעופה דב.</p>\n<p style="text-align: right;">לאחרונה נבנתה בחוף תל ברוך טיילת חדשה וגשר המאפשר את רציפות הטיילת עם אתרים היסטוריים ומחבר את החוף עם גשר הירקון ועם נמל תל-אביב.</p>\n<p style="text-align: right;">צלם:עומר מרקובסקי.מתוך אתר פיקיוויקי.</p>\n<p style="text-align: right;"> </p>',
      VendorId: 34,
      Vendor_Name: 'עיריית תל אביב יפו',
      Product_Url: 'https://info.goisrael.com/he/חוף-תל-ברוך-5326',
      Accessibility: 'כן',
      Address: 'יצחק ארצי, תל אביב-יפו',
      Attraction_Type: 'חופים',
      Blue_Flag: 'כן',
      City: 'תל אביב יפו',
      Diving_beach: 'לא ידוע',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'בתשלום',
      Phone: '<a href="tel:+9723-724-0190">+9723-724-0190</a>',
      Region: 'תל אביב והמרכז',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: 'כן',
      URL: 'https://www.tel-aviv.gov.il/Visitors/Beaches/Pages/TelBaruch.aspx',
      X: 34.7870104,
      Y: 32.1228155,
   },
   {
      _id: 6,
      Id: 5613,
      Name: 'יקב עמק האלה',
      ShortDescription:
         'סוג אטרקציה: יקבים, אזור: ירושלים והסביבה, כתובת: קיבוץ נתיב הל"ה',
      FullDescription:
         '<p style="direction: rtl;">יקב עמק האלה מזמין אתכם ליהנות מחוויה של הסברים חווייתיים על אזור עמק האלה, הכרמים , אופן הכנת היין וייחודיות היקב, וכמובן טעימות של לפחות שלושה סוגי יינות מסדרות שונות. </p>\n<p style="direction: rtl;">האירוח כולל עמדת קפה להתרעננות ובייגלה.</p>\n<p style="direction: rtl;">הביקורים ביקב מתאימים הן לאנשים פרטיים שרוצים להכיר את עולם היין והן לקבוצות מאורגנות שמחפשות חוויה ייחודית ורב חושית.</p>\n<p style="direction: rtl;">לקבוצות של מעל 10 אנשים ניתן לשלב גם סיור ביקב (בהתאם לעבודות היין)</p>\n<p style="direction: rtl;">הביקורים בשפות עברית, רוסית ואנגלית.</p>\n<p style="text-align: right;"> קרדיט לתמונה 3: איל גוטמו</p>\n<p style="text-align: right;"> </p>',
      VendorId: 1908,
      Vendor_Name: 'יקב עמק האלה',
      Product_Url: 'https://info.goisrael.com/he/יקב-עמק-האלה',
      Accessibility: 'כן',
      Address: 'קיבוץ נתיב הל"ה',
      Attraction_Type: 'יקבים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '<a href="mailto:vc@ellavalley.com">vc@ellavalley.com</a>',
      Notes: '',
      Notes_for_opening_hours: 'סיורים: יש לקבוע הגעה בתיאום מראש',
      Opening_Hours:
         'יום ראשון: 09:00 - 16:00,  שני: 09:00 - 16:00, יום שלישי: 09:00 - 16:00, יום רביעי: 09:00 - 16:00, יום חמישי: 09:00 - 16:00, יום שישי: 09:00 - 13:00, יום שבת: סגור',
      Parking: 'כן',
      Phone: '<a href="tel:+972-2-9994885">+972-2-9994885</a>',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'לא',
      Surfing_beach: '',
      URL: 'http://ellavalley.com/en/',
      X: 34.978886,
      Y: 31.687876,
   },
   {
      _id: 7,
      Id: 5634,
      Name: 'יקב ציון',
      ShortDescription:
         'סוג אטרקציה: יקבים, אזור: ירושלים והסביבה, כתובת: חרובית 45, מישור אדומים',
      FullDescription:
         '<p dir="rtl" style="text-align: right;">יקבי ציון, חלוץ היקבים בארץ ישראל, מקפיד על התחדשות בצד מסורת ארוכת שנים אשר שזורה בטכנולוגיות ייצור מתקדמות, טיפול קפדני בכרמים וצוות מקצועי ומיומן. היקב מציע יינות איכות המתאימים לשתייה בכל עת ובכל מעמד.</p>\n<p dir="rtl" style="text-align: right;">מקור היינות בפסיפס ייחודי של ענבים איכותיים מכרמים בגליל, בהרי ירושלים ובשפלת יהודה.</p>\n<p style="text-align: right;">.צלם: שמוליק גבירץ</p>\n<p dir="rtl" style="text-align: right;"> </p>\n<p dir="rtl" style="text-align: right;"> </p>',
      VendorId: 2412,
      Vendor_Name: 'יקב ציון',
      Product_Url: 'https://info.goisrael.com/he/יקב-ציון',
      Accessibility: 'לא',
      Address: 'חרובית 45, מישור אדומים',
      Attraction_Type: 'יקבים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '<a href="mailto:office@zion-winery.com">office@zion-winery.com</a>',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: 'בתיאום מראש בלבד',
      Parking: 'כן',
      Phone: '<a href="tel:+972-2-5352540">+972-2-5352540</a>',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'לא',
      Surfing_beach: '',
      URL: 'http://www.zion-winery.com/',
      X: 35.3417952,
      Y: 31.7884169,
   },
   {
      _id: 8,
      Id: 5674,
      Name: 'יקב כרמל',
      ShortDescription:
         'סוג אטרקציה: יקבים, אזור: צפון, כתובת: רחוב היין 2 (דרך היקב), זכרון יעקב',
      FullDescription:
         '<div dir="rtl">\n<p>מרכז תרבות היין של יקבי כרמל מציע סיורים מודרכים המציגים את ההיסטוריה של היקב, והקמתו בידי הברון אדמונד דה רוטשילד. הסיור כולל גם ביקור במרתפי היין ההיסטוריים, הקרנת סרט קצר, וטעימת יין מודרכת. במקום גם חנות יין המאפשרת אף היא טעימות. הסיורים הם בהזמנה מראש בלבד, לגילאי 18 ומעלה.</p>\n</div>',
      VendorId: 1915,
      Vendor_Name: 'יקב כרמל',
      Product_Url: 'https://info.goisrael.com/he/יקב-כרמל',
      Accessibility: 'נגישות חלקית',
      Address: 'רחוב היין 2 (דרך היקב), זכרון יעקב',
      Attraction_Type: 'יקבים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '<a href="mailto:wineculture@carmelwines.co.il">wineculture@carmelwines.co.il</a>\t',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: 'יש לקבוע הגעה בתיאום מראש.',
      Parking: 'כן',
      Phone: '<a href="tel:+972-4-6391788">+972-4-6391788</a>',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'לא',
      Surfing_beach: '',
      URL: 'http://www.carmelwines.co.il/',
      X: 34.9589951,
      Y: 32.573924,
   },
   {
      _id: 9,
      Id: 5736,
      Name: 'פארק הסלעים בכיסרא-סומיע',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: צפון, כתובת: כיסרא-סומיע',
      FullDescription:
         '<p style="direction: rtl;">פארק סלעי גיר בני כ-90 מיליון שנה שנוצר בתהליך המסה כימית. הפארק בנוי כמבוך ענקי של אבנים וצמחייה סבוכה ויש בו שבילים מסומנים וגם גן משחקים ומסעדה דרוזית.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1921,
      Vendor_Name: 'פארק הסלעים בכיסרא-סומיע',
      Product_Url: 'https://info.goisrael.com/he/kisra-sumei-stone-park-57363',
      Accessibility: 'לא',
      Address: 'כיסרא-סומיע',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: '',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2jVbFnM',
      X: 35.2995685,
      Y: 32.9736987,
   },
   {
      _id: 10,
      Id: 5737,
      Name: 'גן הפסלים בקיבוץ דליה',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: צפון, כתובת: קיבוץ דליה',
      FullDescription:
         '<p style="direction: rtl;">גן הפסלים של חבר הקיבוץ נתן עזרא ינוקא מבטא את רוח המקום ומתמקד בפיסול בתנועה. בגן 24 פסלים בגדלים שונים, בעיקר פיגורטיביים, העשויים שיש, פוליאסטר, ועוד.</p>\n<p style="direction: rtl;">צילום אבישי טייכר מתוך אתר פיקיוויקי</p>',
      VendorId: 1922,
      Vendor_Name: 'גן הפסלים בקיבוץ דליה',
      Product_Url: 'https://info.goisrael.com/he/גן-הפסלים-בקיבוץ-דליה',
      Accessibility: 'כן',
      Address: 'קיבוץ דליה',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: '<a href="tel:+972-4-9897322">+972-4-9897322</a>',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.mapa.co.il/listing/גן-הפסלים-בקיבוץ-דליה/',
      X: 35.06786357,
      Y: 32.58718383,
   },
   {
      _id: 11,
      Id: 5747,
      Name: "פארק הפסלים בכאוכב אבו אל היג'א",
      ShortDescription:
         "סוג אטרקציה: פארקים וגנים, אזור: צפון, כתובת: כאוכב אבו אל היג'א",
      FullDescription:
         '<p style="direction: rtl;">הגן מציג פסלים מודרניים של אמנים ישראלים על רקע נוף הכרמל. השביל היוצא ממנו עובר דרך מיני-אמפיתיאטרון ומטפס על גבעה פורחת. אפשר להמשיך לשדה שבמרכזו באר עתיקה ולשבת תחת עצי הזית.</p>\n<p style="direction: rtl;">קרדיט לתמונה: אבישי טייכר מתוך אתר פיקיוויקי</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1924,
      Vendor_Name: "פארק הפסלים בכאוכב אבו אל היג'א",
      Product_Url:
         'https://info.goisrael.com/he/פארק-הפסלים-בכאוכב-אבו-אל-היגא',
      Accessibility: 'לא',
      Address: "כאוכב אבו אל היג'א",
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: '',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.enjoyingisrael.com/attractions/5747/kaukab-abu-al-hija-sculpture-park',
      X: 35.245417,
      Y: 32.828058,
   },
   {
      _id: 12,
      Id: 5754,
      Name: 'גן פסלי אורסולה מלבין',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: צפון, כתובת: רחוב שדרות הציונות, חיפה',
      FullDescription:
         '<p style="direction: rtl;">על מורדות הכרמל, כמאתיים מטרים מצפון מערב למקדש הבהאי, נמצא גן קטן ומתוק עם 29 פסלי ברונזה יפים שמשתלבים בצמחייה ובשבילים המוצלים, אותם יצרה הפסלת תושבת עין הוד אורסולה מלבין בת השמונים ושתיים.<br />בניגוד לגנים אחרים, שמגלים העדפה לפסלי חוצות ענקיים ומופשטים, הפסלים בגן מתעדים דמויות של ילדים, מבוגרים ובעלי חיים בחיי היומיום.</p>\n<p style="direction: rtl;">צלם: אבישי טייכר. מתוך אתר פיקיוויקי. </p>\n<p style="direction: rtl;"> </p>',
      VendorId: 2407,
      Vendor_Name: 'מפה',
      Product_Url: 'https://info.goisrael.com/he/גן-פסלי-אורסולה-מלבין',
      Accessibility: 'כן',
      Address: 'רחוב שדרות הציונות, חיפה',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: 'חיפה',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'שעת סגירה: 18:00',
      Opening_Hours: '',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-1800-305090">+972-1800-305090</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'http://ein-hod.info/malbin-sculpture/ursula.htm',
      X: 34.9796643,
      Y: 32.81584296,
   },
   {
      _id: 13,
      Id: 5767,
      Name: 'פארק גורן',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: צפון, כתובת: כביש 899 בין סימון קילומטר 11 ל־12',
      FullDescription:
         '<p style="direction: rtl;">פארק הצופה אל נחל כזיב ובו חורש ואתר פיקניק. בנחל זורם פלג מים, ולצד הפלג יש שרידים של טחנות קמח עתיקות, עצי דולב ושיחי ער אציל, שעליו ידועים כעלי דפנה.</p>\n<p style="direction: rtl;">קרדיט לתמונה 1: זהר מאור מתוך אתר פיקיויקי.<br />קרדיט לתמונה 2: דר\' אבישי טייכר,מתוך אתר פיקיויקי.</p>',
      VendorId: 176,
      Vendor_Name: 'קק"ל',
      Product_Url: 'https://info.goisrael.com/he/פארק-גורן',
      Accessibility: 'כן',
      Address: 'כביש 899 בין סימון קילומטר 11 ל־12',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: '<a href="tel:1-800-350550">1-800-350550</a>',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2lTWqMs',
      X: 35.228542,
      Y: 33.0539,
   },
   {
      _id: 14,
      Id: 5768,
      Name: 'חורבת סעדים',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: ירושלים והסביבה, כתובת: חורבת סעדים',
      FullDescription:
         '<p style="direction: rtl;">חורבת סעדים יושבת על רכס שמפריד בין נחל שורק ונחל רפאים.</p>\n<p style="direction: rtl;">לרגלי החורבה, בין האורנים שנטעה הקרן הקיימת, הוצבו שולחנות פיקניק וברזיות, ומעט מעליהם, במדרון המיוער, יש מתקני משחק לילדים.</p>\n<p style="direction: rtl;">צלם: אסנת יותם. מתוך אתר פיקיוויקי.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 2407,
      Vendor_Name: 'מפה',
      Product_Url: 'https://info.goisrael.com/he/חורבת-סעדים',
      Accessibility: 'כן',
      Address: 'חורבת סעדים',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: '',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.enjoyingisrael.com/attractions/5768/seadim-ruins',
      X: 35.13022609,
      Y: 31.75075662,
   },
   {
      _id: 15,
      Id: 5812,
      Name: 'פארק הקישון',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: צפון, כתובת: רחוב הדייגים, מעגן הדייג, חיפה',
      FullDescription:
         '<p style="direction: rtl; text-align: right; padding-left: 30px;">כדאי להגיע לפארק הקישון, בשפך הנחל אל הים, כדי להתרשם מהצלחת המאמצים.</p>\n<p style="direction: rtl; text-align: right; padding-left: 30px;">במדשאות גדולות על גדת הנחל אפשר ליהנות מטבע אמיתי בלב ההמולה האורבנית של מפרץ חיפה.</p>\n<p style="direction: rtl; text-align: right; padding-left: 30px;">אל תתפלאו אם לנגד עיניכם יעברו מינים שונים של ציפורים כמו קורמורנים, שלדגים, אנפות, מגלנים ואגמיות. אולי תתקלו גם באחת הסדנאות לגוף ולנפש, בטיבוע ציפורים או בקבלת שבת מאורגנת שמתקיימים פה תכופות.</p>\n<p style="direction: rtl; text-align: right; padding-left: 30px;">כמובן שגם כאן יש תוכניות לעתיד, בתקווה שבעוד כמה שנים פארק הקישון יהיה רק חלק קטן מפארק ענק שיקום במורד נחל קישון ובו מרכז מבקרים חינוכי שיניע פעילות קהילתית סביב שיקומו של הנחל.</p>\n<p style="direction: rtl; text-align: right; padding-left: 30px;">קרדיט לתמונה: יהודית גרעין-כל . מתוך אתר פיקיוויקי.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 2406,
      Vendor_Name: 'רשות נחל הקישון',
      Product_Url: 'https://info.goisrael.com/he/פארק-הקישון',
      Accessibility: 'כן',
      Address: 'רחוב הדייגים, מעגן הדייג, חיפה',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: 'חיפה',
      Diving_beach: '',
      Email: ' <a href="mailto:info@kishon.org.il\t"> info@kishon.org.il\t </a> ',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-4-8404404">+972-4-8404404</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2kjp3SV',
      X: 35.0305546,
      Y: 32.8040947,
   },
   {
      _id: 16,
      Id: 5813,
      Name: 'פארק עד הלום',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: דרום, כתובת: הכניסה הדרומית לאשדוד',
      FullDescription:
         '<p style="direction: rtl;">פארק המציין את פיצוץ גשר עד הלום שנמצא בנקודה שעד אליה הגיע צבא מצרים במלחמת העצמאות. במקום אנדרטה לחללי חטיבת גבעתי ואנדרטה שהקימה מצרים לזכר חלליה. בפארק עמדה מצרית מבטון ולוחות לציון מצביאים מפורסמים שעברו באזור.</p>\n<p style="direction: rtl;">קרדיט לתמונה: דר\' אבישי טייכר. מתוך אתר פיקיויקי.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1211,
      Vendor_Name: 'טבע ונופים בישראל',
      Product_Url: 'https://info.goisrael.com/he/פארק-עד-הלום',
      Accessibility: 'לא',
      Address: 'הכניסה הדרומית לאשדוד',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: 'אשדוד',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: '',
      Region: 'דרום',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2lCYvMw',
      X: 34.668606,
      Y: 31.785614,
   },
   {
      _id: 17,
      Id: 5828,
      Name: 'מוזיאון לארכיאולוגיה אזורית וים תיכונית בגן הלאומי',
      ShortDescription:
         'סוג אטרקציה: מוזיאונים ותרבות, אזור: צפון, כתובת: גן השלושה (הסחנה)',
      FullDescription:
         '<p style="text-align: right;">המוזיאון לארכאולוגיה אזורית וים-תיכונית בגן הלאומי גן השלושה במוזיאון, שהוא חלק ממתחם גדול יותר המתאר את סיפורו של עמק יזרעאל המקיף את האתר, מוצגים כלים ופסלונים ייחודים יפהפיים המשקפים את מגוון התרבויות שפרחו באזורנו, כולל תרבויות יוון, פרס, מצרים והתרבות האטרוסקית. במקום מוצגים גם שרידים ארכיטקטוניים ורחוב ראשי משוחזר מבית שאן של התקופה הביזנטית, כך שהביקור במוזיאון יכול להתלוות לביקור בגן הלאומי בית שאן הנמצא בקרבת מקום. המוזיאון משמש אכסניה לאירועי ספורט לבני נוער בסימן הרוח האולימפית של העת העתיקה, רוח ה-Ekecheiria , הפסקת האש שהתקיימה בתקופת המשחקים האולימפיים.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 346,
      Vendor_Name: 'גן השלושה',
      Product_Url:
         'https://info.goisrael.com/he/מוזיאון-לארכיאולוגיה-אזורית-וים-תיכונית-בגן-הלאומי',
      Accessibility: 'כן',
      Address: 'גן השלושה (הסחנה)',
      Attraction_Type: 'מוזיאונים ותרבות',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: ' <a href="mailto:mus@gan3.co.il\t"> mus@gan3.co.il\t </a> ',
      Notes: '',
      Notes_for_opening_hours: 'קבוצות: יש לקבוע הגעה בתיאום מראש',
      Opening_Hours:
         'יום ראשון: 10:00 - 14:00, יום שני: 10:00 - 14:00, יום שלישי: 10:00 - 14:00, יום רביעי: 10:00 - 14:00, יום חמישי: 10:00 - 14:00, יום שישי: סגור, יום שבת: סגור',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-4-6586352">+972-4-6586352</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/33cPrhU',
      X: 35.450768,
      Y: 32.50459,
   },
   {
      _id: 18,
      Id: 5857,
      Name: 'גן החיות הלימודי',
      ShortDescription:
         'סוג אטרקציה: טבע ובעלי חיים, אזור: צפון, כתובת: רחוב התשבי 124, חיפה',
      FullDescription:
         '<p style="direction: rtl;">גן החיות, שנוסד ב-1948, ממוקם בקצה גן האם והוא מגני החיות הוותיקים בארץ.</p>\n<p style="direction: rtl;">בגן כלובים ענקיים שבהם אפשר לבקר ולחוש את סביבת המחיה האופיינית לדייריהם.</p>\n<p style="direction: rtl;">אפשר לראות כאן את הסורקיטה, מין נמייה שעומדת כשהיא נשענת על זנבה, את הדוב הסורי החום שהוא חלק מתצוגת הדובים הגדולה בארץ, את הלמורים שנראים כמו קופים אבל הם לא, ואת העופות הדורסים.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1937,
      Vendor_Name: 'גן החיות הלימודי',
      Product_Url: 'https://info.goisrael.com/he/גן-החיות-הלימודי',
      Accessibility: 'כן',
      Address: 'רחוב התשבי 124, חיפה',
      Attraction_Type: 'טבע ובעלי חיים',
      Blue_Flag: '',
      City: 'חיפה',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         'קיץ: יום ראשון: 09:00 - 18:00, שני: 09:00 - 18:00, יום שלישי: 09:00 - 18:00, יום רביעי: 09:00 - 18:00, יום חמישי: 09:00 - 18:00, יום שישי וערבי חג: 09:00 - 14:00, יום שבת: 09:00 - 18:00\nחורף: יום ראשון: 09:00 - 16:00, שני: 09:00 - 16:00, יום שלישי: 09:00 - 16:00, יום רביעי: 09:00 - 16:00, יום חמישי: 09:00 - 16:00, יום שישי וערבי חג: 08:00 - 13:00, יום שבת: 08:00 - 16:00',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-4-8372886">+972-4-8372886</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'http://www.haifazoo.co.il',
      X: 34.98565428,
      Y: 32.80740008,
   },
   {
      _id: 19,
      Id: 5859,
      Name: 'גן הקקטוסים והגן היפני, חולון',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: תל אביב והמרכז, כתובת: שדרות ירושלים 85, חולון',
      FullDescription:
         '<p style="direction: rtl;">שני גנים ציבוריים לאורך שדרות ירושלים: גן הקקטוסים שבו כ-600 זני קקטוס וגם מפל מים ופסלים, והגן היפני - גן הבנוי בסגנון יפני מסורתי.</p>\n<p style="direction: rtl;">יש בו מפל מים מרכזי, ביתן תה השוכן במרכז אגם, צמחייה מיוחדת ופרגולות במבוק.</p>\n<p style="direction: rtl;">קרדיט לתמונה: אבישי טייכר.מתוך אתר פיקיוויקי.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 2317,
      Vendor_Name: 'עיריית חולון',
      Product_Url: 'https://info.goisrael.com/he/גן-הקקטוסים-והגן-היפני-חולון',
      Accessibility: 'כן',
      Address: 'שדרות ירושלים 85, חולון',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: 'חולון',
      Diving_beach: '',
      Email: ' <a href="mailto:gnkaktus@netvision.net.il\t"> gnkaktus@netvision.net.il\t </a> ',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         'יום ראשון: 08:30 - 14:30,  יום שני: 08:30 - 14:30, יום שלישי: 08:30 - 14:30, יום רביעי: 08:30 - 14:30, יום חמישי: 08:30 - 14:30, יום שישי: סגור, יום שבת: 10:00 - 14:00, ערב חג: 08:30 - 12:00',
      Parking: 'בתשלום',
      Phone: ' <a href="tel:+972-3-5027422">+972-3-5027422</a> ',
      Region: 'תל אביב והמרכז',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2p1LjTH',
      X: 34.793703,
      Y: 32.011642,
   },
   {
      _id: 20,
      Id: 5885,
      Name: 'גן לאומי תל גזר',
      ShortDescription:
         'סוג אטרקציה: אתרים לאומיים, ארכיאולוגיה והיסטוריה, אזור: תל אביב והמרכז, כתובת: כרמי יוסף',
      FullDescription:
         '<p style="direction: rtl;">תל שסביבו שרידים מתקופת הברונזה התיכונה ומראשית תקופת המלוכה. אחד השרידים המרשימים הוא מפעל המים של גזר, שהוקם בתקופה הכנענית או בתקופת המלוכה.</p>\n<p style="direction: rtl;">במקום גם קבר שייח\' הרוס מהמאה ה-16 וקברים מוסלמיים נוספים.</p>\n<p style="direction: rtl;">קרדיט לתמונה: אודי שטיינוול. מתוך אתר פיקיוויקי.</p>',
      VendorId: 1211,
      Vendor_Name: 'טבע ונופים בישראל',
      Product_Url: 'https://info.goisrael.com/he/גן-לאומי-תל-גזר',
      Accessibility: 'לא',
      Address: 'כרמי יוסף',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה;אתרים לאומיים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-2-5006261">+972-2-5006261</a> ',
      Region: 'תל אביב והמרכז',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'http://bit.ly/2mf0uCX',
      X: 34.919663,
      Y: 31.860013,
   },
   {
      _id: 21,
      Id: 5893,
      Name: 'גן לאומי בית שאן',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: צפון, כתובת: בית שאן',
      FullDescription:
         '<p style="direction: rtl; text-align: right;">בית שאן, השוכנת בעמק בית שאן דרומית לכנרת, הוקמה לפני כ-6,000 שנה, ונזכרת בתנ"ך בסיפור תבוסתו המרה של המלך שאול על הר גלבוע הנמצא בקרבת מקום.</p>\n<p style="direction: rtl; text-align: right;">לפני כ-2,300 שנה הוקמה העיר מחדש כעיר הלניסטית. היא עלתה לגדולה בתקופת השלטון הרומי והביזנטי, אבל נחרבה ברעש אדמה שפקד את האזור בשנת 749 לספירה.</p>\n<p style="direction: rtl; text-align: right;">שרידיה של העיר המפוארת - רחובות העמודים המרשימים, בית המרחץ, התיאטרון והמקדשים שוחזרו למרגלות תל בית שאן המקראי בגן הלאומי בית שאן.</p>\n<p style="direction: rtl; text-align: right;">אל תחמיצו את חוויית המולטימדיה הרב-חושית הייחודית – חיזיון "לילות שאן".</p>\n<p style="direction: rtl; text-align: right;">קרדיט לתמונה: שאולה הייטנר. מתוך אתר פיקיוויקי.</p>\n<p style="direction: rtl; text-align: right;"> </p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/גן-לאומי-בית-שאן',
      Accessibility: 'כן',
      Address: 'בית שאן',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: 'בית שאן',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00,  שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-4-6587189">+972-4-6587189</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2NIRu7b',
      X: 35.500348,
      Y: 32.501333,
   },
   {
      _id: 30,
      Id: 6052,
      Name: 'כנסיית אנה',
      ShortDescription:
         'סוג אטרקציה: מקומות קדושים, אזור: ירושלים והסביבה, כתובת: הרובע המוסלמי, ליד שער האריות, העיר העתיקה, ירושלים',
      FullDescription:
         '<p style="direction: rtl;">הכנסייה נבנתה על ידי צלבנים, וב-1192 שונה ייעודה לבית ספר איסלמי.</p>\n<p style="direction: rtl;">הכנסייה נותרה ללא שימוש במשך שנים רבות, עד לשנת 1856 כאשר השלטון העותמני העניק אותה לצרפת. הכנסייה עדיין מנוהלת על ידי כמרים צרפתים.</p>\n<p style="direction: rtl;"> </p>\n<p style="direction: rtl;"> </p>',
      VendorId: 418,
      Vendor_Name: 'אתר התיירות של ירושלים',
      Product_Url: 'https://info.goisrael.com/he/כנסיית-אנה',
      Accessibility: 'כן',
      Address: 'הרובע המוסלמי, ליד שער האריות, העיר העתיקה, ירושלים',
      Attraction_Type: 'מקומות קדושים',
      Blue_Flag: '',
      City: 'ירושלים',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         'יום ראשון: סגור, יום שני: 08:00 - 12:00, 14:00 - 17:00, יום שלישי: 08:00 - 12:00, 14:00 - 17:00, יום רביעי: 08:00 - 12:00, 14:00 - 17:00, יום חמישי: 08:00 - 12:00, 14:00 - 17:00, יום שישי: 08:00 - 12:00, 14:00 - 17:00, יום שבת: 08:00 - 12:00, 14:00 - 17:00',
      Parking: 'לא',
      Phone: ' <a href="tel:+972-2-6283285">+972-2-6283285</a> ',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.seetheholyland.net/church-of-st-anne/',
      X: 35.236074,
      Y: 31.78113,
   },
   {
      _id: 22,
      Id: 5917,
      Name: 'פארק הרודיון',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אתרים לאומיים, אזור: ירושלים והסביבה, כתובת: פארק הרודיון',
      FullDescription:
         '<p style="direction: rtl;">מבצר הרודיון, הניצב בראש גבעה מלאכותית מחוץ לבית לחם, עלה לאחרונה לכותרות ברחבי העולם בעקבות גילוי קברו של הורדוס אחרי שנים רבות של חיפושים.</p>\n<p style="direction: rtl;">סיור באתר כולל את הקבר, את מגדלי השמירה הגדולים של המבצר-הארמון שבנה הורדוס, את החצרות, את בית המרחץ, בית כנסת שבנו מורדים יהודים בתקופת המרד הגדול ורשת של מחילות מסתור שבנו הלוחמים היהודים.</p>\n<p style="direction: rtl;">קרדיט לתמונות: אתר PikiWiki</p>\n<p style="direction: rtl;"> שימו לב!<br />בעקבות משבר הקורונה קיימת הגבלה של מספר המבקרים באתרי רט"ג ונדרש רישום מראש. <a href="https://www.parks.org.il/%D7%94%D7%96%D7%9E%D7%A0%D7%95%D7%AA-%D7%9C%D7%90%D7%AA%D7%A8%D7%99%D7%9D/#1" target="_blank">לינק להרשמה</a>.</p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/הגן-הלאומי-הרודיון',
      Accessibility: 'כן',
      Address: 'פארק הרודיון',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה;אתרים לאומיים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: ' <a href="mailto:gl-erodyon@npa.org.il">gl-erodyon@npa.org.il</a>',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00,  שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: '<a href="tel:+972-4-2-5953591">+972-2-5953591</a>',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2XDkh1z',
      X: 35.241682,
      Y: 31.665741,
   },
   {
      _id: 23,
      Id: 5924,
      Name: 'גן לאומי כפר נחום',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: צפון, כתובת: גן לאומי כפר נחום',
      FullDescription:
         '<p style="direction: rtl;">הגן הלאומי ושרידי כפר דייגים מתקופת בית שני, שבו קבע ישו את מרכז פעילותו הדתית בגליל.</p>\n<p style="direction: rtl;">אתר העתיקות מוחזק כיום על-ידי הכנסייה הפרנציסקנית.</p>\n<p style="direction: rtl;">הגן הלאומי שמסביב לאתר העתיקות, מוחזק על-ידי רשות הטבע והגנים.</p>\n<p style="direction: rtl;">הגן הלאומי כולל טיילת שאורכה 3.5 ק"מ המחברת בין כפר נחום לטבחה. ממזרח לעתיקות כפר נחום נבנה מזח צף, העולה ויורד עם מפלס המים.</p>\n<p style="direction: rtl;">המתקנים שעל המזח כוללים תחנת מידע, חנות מזכרות שירותים ומזנון. בגן מטפחים ומשמרים מגוון של צמחים ובעלי חיים.</p>\n<p style="direction: rtl;">קרדיט לתמונה: שאולה הייטנר. מתוך אתר פיקיוויקי.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/גן-לאומי-כפר-נחום',
      Accessibility: 'לא ידוע',
      Address: 'גן לאומי כפר נחום',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00</br> חורף: יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-4-6793865">+972-4-6793865</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2lVgyy0',
      X: 35.578344,
      Y: 32.883107,
   },
   {
      _id: 24,
      Id: 5927,
      Name: 'גן לאומי כורסי',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: צפון, כתובת: גן לאומי כורסי',
      FullDescription:
         '<p style="direction: rtl;">בגן הלאומי כורסי, לחופה המזרחי של הכינרת, נמצאים שרידי מנזר ביזנטי מהמאה החמישית וכנסייה המציינת את המקום שבו התרחש, לפי המסופר בברית החדשה, "נס החזירים", שביצע ישו, כשגירש את השדים שאחזו בשני אנשים, ושילח אותם לתוך עדר חזירים ששעטו במורד גבעה לכינרת וטבעו.</p>\n<p style="direction: rtl;">רצפת בית הכנסת מתארת בעלי חיים, עופות ופירות. במקום אפשר גם לראות בית בד עתיק או לטפס בשביל העולה לראש הגבעה המפורסמת.</p>\n<p style="direction: rtl;">קרדיט לתמונה: טלמור יאיר באמצעות וויקישיתוף.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/גן-לאומי-כורסי',
      Accessibility: 'כן',
      Address: 'גן לאומי כורסי',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00,  יום שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00,  יום שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-4-6731983">+972-4-6731983</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2nvMqdf',
      X: 35.650356,
      Y: 32.826163,
   },
   {
      _id: 25,
      Id: 5947,
      Name: 'גן לאומי ומשמורת טבע ארבל',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: צפון, כתובת: שמורת טבע ארבל',
      FullDescription:
         '<p style="text-align: right;">בגן הלאומי ארבל נמצאים שרידי בית כנסת מפואר ביניהם כותרות גדולות של עמודים קורינתיים. שביל מעגלי מוליך אל מצפור החרוב המשקיף על הכינרת. ובמקום נמצאת גם דרך הרומית העתיקה. ההרפתקנים ימצאו במקום מגוון שבילים למיטיבי לכת. אחד השבילים ייקח אתכם במורד המצוק התלול למצודת המערות, שבהן הסתתרו יהודים שמרדו בהורדוס. במקום זה אפשר עדיין לראות ביצורים מרשימים מהמאה ה-18.</p>\n<p style="text-align: right;">קרדיט לתמונה: יורם שפירר</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/גן-לאומי-ארבל',
      Accessibility: 'לא ידוע',
      Address: 'שמורת טבע ארבל',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00,  שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: '<a href="tel:+972-4-6732904">+972-4-6732904</a>',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2vYICC1',
      X: 35.498566,
      Y: 32.824503,
   },
   {
      _id: 26,
      Id: 5979,
      Name: 'שמורת טבע עין גדי',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: ים המלח, כתובת: שמורת טבע עין גדי',
      FullDescription:
         '<p style="direction: rtl;">הגן הלאומי עתיקות עין גדי בגן הלאומי עתיקות עין גדי, שהוא חלק משמורת הטבע עין גדי, נמצאים שרידי יישוב יהודי שהתקיים במקום בין המאות השלישית לשישית לספירה.</p>\n<p style="direction: rtl;">בחפירות שנערכו במקום נחשפו מבני מגורים ובית כנסת.</p>\n<p style="direction: rtl;">המבנים הסמוכים לבית הכנסת שימשו כנראה למגורי שמשי בית הכנסת או ששימשו כאולמות לימוד ואכסניה.</p>\n<p style="direction: rtl;">רצפת בית הכנסת העתיק כוללת כתובת מסקרנת שעניינה שמירת סוד.</p>\n<p style="direction: rtl;">יש חוקרים הסבורים שהיא קשורה לייצור בושם האפרסמון בעל הניחוח המשובח שהיה שווה את משקלו בזהב. משיחי האפרסמון (לא האפרסמון שאנחנו מכירים כיום) שגידלו התושבים על המדרגות לעיבוד חקלאי הפיקו גם חומר משחתי בעל סגולות רפואיות.</p>\n<p style="direction: rtl;">קרדיט לתמונה: שלומי קקון. מתוך אתר פיקיוויקי.</p>\n<p style="direction: rtl;"> </p>\n<p style="direction: rtl;">ימו לב!<br />בעקבות משבר הקורונה קיימת הגבלה של מספר המבקרים באתרי רט"ג ונדרש רישום מראש. <a href="https://www.parks.org.il/%D7%94%D7%96%D7%9E%D7%A0%D7%95%D7%AA-%D7%9C%D7%90%D7%AA%D7%A8%D7%99%D7%9D/#1" target="_blank">לינק להרשמה</a>.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/גן-לאומי-עתיקות-עין-גדי',
      Accessibility: 'כן',
      Address: 'שמורת טבע עין גדי',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '<a href="mailto:st-eingedi@npa.org.il">st-eingedi@npa.org.il</a>',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00,  יום שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00,  יום שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-8-6584285">+972-8-6584285</a> ',
      Region: 'ים המלח',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2SMevqD',
      X: 35.387773,
      Y: 31.466637,
   },
   {
      _id: 27,
      Id: 5983,
      Name: 'גן לאומי הבשור - פארק אשכול',
      ShortDescription:
         'סוג אטרקציה: פארקים וגנים, אזור: דרום, כתובת: גן לאומי הבשור פארק אשכול',
      FullDescription:
         '<p style="direction: rtl;">גן לאומי הבשור הוא פינה ירוקה במדבר על גדת נחל בשור. בגן הלאומי נובע מעיין שופע וסביבו מדשאות רחבות ידיים ואלפי עצים נותני צל. גן לאומי הבשור הוא מקום נפלא לבילוי בחיק הטבע ובסיס יציאה מצוין לטיולים במרחבי חבל הבשור. <br />בגן שולחנות פיקניק, שחזור גשר רכבת מימי המנדט, אתר עתיקות מהתקופה המצרית הקדומה, שני מסלולים קלים לאופניים וחניון לילה מוסדר.</p>\n<p style="direction: rtl;"> שימו לב!<br />בעקבות משבר הקורונה קיימת הגבלה של מספר המבקרים באתרי רט"ג ונדרש רישום מראש. <a href="https://www.parks.org.il/%D7%94%D7%96%D7%9E%D7%A0%D7%95%D7%AA-%D7%9C%D7%90%D7%AA%D7%A8%D7%99%D7%9D/#1" target="_blank">לינק להרשמה</a>.</p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/גן-לאומי-אשכול',
      Accessibility: 'כן',
      Address: 'גן לאומי הבשור פארק אשכול',
      Attraction_Type: 'פארקים וגנים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00,  יום שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00,  יום שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: '<a href="tel:+972-8-9985110">+972-8-9985110</a>',
      Region: 'דרום',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2lkn2GG',
      X: 34.489392,
      Y: 31.308486,
   },
   {
      _id: 28,
      Id: 5996,
      Name: 'גן לאומי ברעם',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: צפון, כתובת: גן לאומי ברעם',
      FullDescription:
         '<p style="direction: rtl;">הגן הלאומי ברעם בית כנסת הקדום של הכפר ברעם שנבנה במאה השלישית לספירה שוכן בתוך יער יפהפה של עצי אורן עתיקים. פיתוחי האבן המעטרים את פתחי בית הכנסת הם עדות לכך שהקהילה שהקימה אותו לא חסכה משאבים ומאמץ בהקמת מבנה מפואר שתוכל להתגאות בו. בעמדכם באכסדרת העמודים ששימשה פעם לתפילה, ללימוד ולמפגש, תוכלו לראות בעיני רוחכם את בית הכנסת בכל הדרו. בית הכנסת בנוי בסגנון הבזיליקה המאפיין גם בתי כנסת גליליים אחרים דוגמת כפר נחום וכורזים.</p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/גן-לאומי-ברעם',
      Accessibility: 'כן',
      Address: 'גן לאומי ברעם',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00',
      Opening_Hours:
         'שעון קיץ: יום ראשון: 08:00 - 17:00,  שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> שעון חורף: יום ראשון: 08:00 - 16:00,  שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: '<a href="tel:+972-4-6989301">+972-4-6989301</a>',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2kwl05R',
      X: 35.415324,
      Y: 33.044006,
   },
   {
      _id: 29,
      Id: 6031,
      Name: 'גן לאומי כורזים',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: צפון, כתובת: גן לאומי כורזים',
      FullDescription:
         '<p style="direction: rtl; text-align: right;">העיר היהודית כורזים שגשגה בשלהי תקופת התלמוד. כורזים נזכרת בברית החדשה כאחת משלוש הערים שישו היטיב להכיר. בית הכנסת היפהפה בכורזים, הבנוי כולו מאבני בזלת, נבנה במאה הרביעית והחמישית ואפשר לראות בו עיטורים מסותתים באבן הבזלת – צורות גאומטריות, צמחים ובעלי חיים וכן את כורסת הבזלת המשוחזרת - "קתדרא דמשה". סמוך לבית הכנסת התגלה מקווה טהרה עתיק. באתר שוחזרו שני בתי מגורים מפוארים ובית בד.</p>\n<p style="direction: rtl; text-align: right;">קרדיט לתמונה: אבי ברק מתוך פיקיוויקי</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url: 'https://info.goisrael.com/he/כורזים',
      Accessibility: 'לא',
      Address: 'גן לאומי כורזים',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: 'ערב יום כיפור: 08:00 - 13:00, יום כיפור: סגור',
      Opening_Hours:
         'קיץ: יום ראשון: 08:00 - 17:00, יום שני: 08:00 - 17:00, יום שלישי: 08:00 - 17:00, יום רביעי: 08:00 - 17:00, יום חמישי: 08:00 - 17:00, יום שישי: 08:00 - 16:00, יום שבת: 08:00 - 17:00, ערב חג: 08:00 - 16:00</br> חורף: יום ראשון: 08:00 - 16:00, יום שני: 08:00 - 16:00, יום שלישי: 08:00 - 16:00, יום רביעי: 08:00 - 16:00, יום חמישי: 08:00 - 16:00, יום שישי: 08:00 - 15:00, יום שבת: 08:00 - 16:00, ערב חג: 08:00 - 15:00',
      Parking: 'כן',
      Phone: '<a href="tel:+972-4-6934982">+972-4-6934982</a>',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2SP1o8h',
      X: 35.564977,
      Y: 32.912249,
   },
   {
      _id: 31,
      Id: 6059,
      Name: 'כנסיית הביקור',
      ShortDescription:
         'סוג אטרקציה: מקומות קדושים, אזור: ירושלים והסביבה, כתובת: עין כרם, ירושלים',
      FullDescription:
         '<p style="direction: rtl;">כנסייה זו, השוכנת בראש גבעה בעין כרם שליד ירושלים, מוקדשת לביקור שערכה מרים, אמו של ישו, אצל אליזבט, אמו של יוחנן המטביל. כששתי הנשים נפגשו, השמיעה מרים את שיר ההלל שלה, ה"מגניפיקט". על קירות חצר הכנסייה תלויים 47 לוחות קרמיקה ועליהם תפילת המגניפקט ב-47 לשונות שונות. גן שלו מחבר את המערה-בית התפילה שם התקיימה, לפי המסורת, פגישתן של מרים ואליזבט, אל הכנסייה המפוארת שמעליה.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1955,
      Vendor_Name: 'כנסיית הביקור',
      Product_Url: 'https://info.goisrael.com/he/כנסיית-הביקור-60593',
      Accessibility: 'לא',
      Address: 'עין כרם, ירושלים',
      Attraction_Type: 'מקומות קדושים',
      Blue_Flag: '',
      City: 'ירושלים',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         'יום ראשון: 12:00-08:00, 18:00-14:30  יום שני: 12:00-08:00, 18:00-14:30,  יום שלישי:  12:00-08:00, 18:00-14:30 , ום רביעי:  12:00-08:00, 18:00-14:30,  יום חמישי:  12:00-08:00, 18:00-14:30  יום שישי:  12:00-08:00, 18:00-14:30 ,  יום שבת:  12:00-08:00, 18:00-14:30 ',
      Parking: 'כן',
      Phone: '<a href="tel:+972-2-6417291">+972-2-6417291</a>',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.tripadvisor.co.il/Attraction_Review-g488156-d1754515-Reviews-Church_of_the_Visitation-Ein_Kerem_Jerusalem_District.html',
      X: 35.1594527,
      Y: 31.7647091,
   },
   {
      _id: 32,
      Id: 6120,
      Name: 'כנסיית הקבר',
      ShortDescription:
         'סוג אטרקציה: מקומות קדושים, אזור: ירושלים והסביבה, כתובת: ויה דולורוזה, העיר העתיקה, ירושלים',
      FullDescription:
         '<p style="direction: rtl;">כנסיית הקבר, על פי המסורת הנוצרית כנסיית הקבר בנויה על אתר צליבתו של ישו, כאן הוא קבור, וזהו המקום הקדוש והחשוב ביותר לנוצרים קתולים ואורתודוכסים.</p>\n<p style="direction: rtl;">הכנסייה נמצאת בשליטת שש רשויות דת שונות, נקבעו בה שעות תפילה נפרדות לכל עדה ופעם בשנה מתכנסים ראשי העדות השונות לדון בבעיות משותפות.</p>\n<p style="direction: rtl;">עבודות השחזור הסתיימו, וגם אם הייתם פעם - כדאי לחזור.</p>\n<p style="direction: rtl;">צלם: יהודית גרעין-כל. מתוך אתר פיקיוויקי.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 293,
      Vendor_Name: 'הכל על ירושלים ',
      Product_Url: 'https://info.goisrael.com/he/כנסיית-הקבר',
      Accessibility: 'לא',
      Address: 'ויה דולורוזה, העיר העתיקה, ירושלים',
      Attraction_Type: 'מקומות קדושים',
      Blue_Flag: '',
      City: 'ירושלים',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         ' יום ראשון:  סגור  שני:   08:30-12:00, 14:00-17:30, יום שלישי:  08:30-12:00, 14:00-17:30,  יום רביעי:   08:30-12:00, 14:00-17:30, יום חמישי:   08:30-12:00, 14:00-17:30, יום ששי:  08:30-12:00, 14:00-17:30, שבת:  08:30-12:00, 14:00-17:30',
      Parking: 'לא',
      Phone: '',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'http://bit.ly/2mVPhHs',
      X: 35.230823,
      Y: 31.7787993,
   },
   {
      _id: 33,
      Id: 6124,
      Name: 'כנסיית מריה מגדלנה',
      ShortDescription:
         'סוג אטרקציה: מקומות קדושים, אזור: ירושלים והסביבה, כתובת: הר הזיתים, ירושלים',
      FullDescription:
         '<p style="direction: rtl;">הכנסייה הרוסית אורתודוקסית שעל הר הזיתים נבנתה בשנת 1895 על-ידי הצאר אלכסנדר ה-3 לזכר אמו, מריה אלכסנדרובנה, והיא נקראת על-שם הקדושה הפטרונית שלה, מריה מגדלנה (מרים המגדלית). הכנסייה על שבע כיפותיה המוזהבות המרהיבות דמויות הבצלים, הבנויה בסגנון הכנסיות שנבנו במוסקבה במאה ה-16, היא אחד האתרים הידועים ביותר בירושלים. הכנסייה היא גם מקום קבורתה של "הגויה הצדקת", הנסיכה אליס מיוון, סבתו של הנסיך צ\'ארלס מצד אביו. מהגן היפהפה של הכנסייה נשקף מראהו עוצר הנשימה של שער הרחמים הקבוע בחומות העיר העתיקה.</p>\n<p style="direction: rtl;"> </p>\n<p style="direction: rtl;">צילום: רנבר, מקסים דופלי מתוך פיקיוויקי</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1964,
      Vendor_Name: 'כנסיית מריה מגדלנה',
      Product_Url: 'https://info.goisrael.com/he/כנסיית-מריה-מגדלנה',
      Accessibility: 'לא',
      Address: 'הר הזיתים, ירושלים',
      Attraction_Type: 'מקומות קדושים',
      Blue_Flag: '',
      City: 'ירושלים',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         ' יום ראשון: סגור,  יום שני: סגור, יום שלישי: 10:00-12:00, יום רביעי:  סגור, יום חמישי: 10:00-12:00, יום שישי: סגור, יום שבת: סגור',
      Parking: 'לא',
      Phone: '<a href="tel:+972-2-6284371">+972-2-6284371</a>',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'לא',
      Surfing_beach: '',
      URL: 'http://www.jerusalem-mission.org/convent_magdalene.html',
      X: 35.2394866,
      Y: 31.7788807,
   },
   {
      _id: 34,
      Id: 6125,
      Name: 'כנסיית מרקוס הקדוש הסורית אורתודוקסית',
      ShortDescription:
         'סוג אטרקציה: מקומות קדושים, אזור: ירושלים והסביבה, כתובת: העיר העתיקה, ירושלים',
      FullDescription:
         '<p style="direction: rtl;">כנסיית מרקוס הקדוש שייכת לאחד מזרמי הנצרות הקדומים ביותר בארץ הקודש: האורתודוקסים הסורים.</p>\n<p style="direction: rtl;">בימי קדם התפתחה מסורת האומרת שהסעודה האחרונה והמקום שבו החלו השליחים לדבר בלשונות רבות, אירוע שגם הוא התרחש לפי המסורת על הר ציון הנמצא בקרבת מקום, התרחשו בביתו של יוחנן מרקוס.</p>\n<p style="direction: rtl;">במקום קדוש זה נמצאת כתובת מהמאה השישית בשפה הסורית האומרת: "זה ביתה של מרים אמו של יוחנן מרקוס".</p>\n<p style="direction: rtl;">השפה הסורית, הקרובה לארמית שהייתה שפתו של ישו, שגורה עדיין בפי בני הקהילה.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 49,
      Vendor_Name: 'רשות הטבע והגנים',
      Product_Url:
         'https://info.goisrael.com/he/כנסיית-מרקוס-הקדוש-הסורית-אורתודוקסית',
      Accessibility: 'לא',
      Address: 'העיר העתיקה, ירושלים',
      Attraction_Type: 'מקומות קדושים',
      Blue_Flag: '',
      City: 'ירושלים',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         'יום ראשון:  07:30 - 18:00,  שני:  07:30 - 18:00, יום שלישי:  07:30 - 18:00, יום רביעי:  07:30 - 18:00,, יום חמישי:  07:30 - 18:00, יום שישי:  07:30 - 18:00, יום שבת: 07:30 - 18:00',
      Parking: 'לא',
      Phone: ' <a href="tel:+972-2-6283304">+972-2-6283304</a> ',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.seetheholyland.net/tag/syriac-orthodox/',
      X: 35.2278448,
      Y: 31.777203,
   },
   {
      _id: 35,
      Id: 6137,
      Name: "כנסיית ג'ורג' הקדוש בלוד",
      ShortDescription:
         'סוג אטרקציה: מקומות קדושים, אזור: תל אביב והמרכז, כתובת: לוד',
      FullDescription:
         '<p style="direction: rtl;">בלוד, העיר שבא ריפא פטרוס את אניאס, שוכנת אחת הקהילות הנוצריות הקדומות ביותר בארץ הקודש. במקום זה נולד, לפי המסורת, גאורגיוס (ג\'ורג\') הקדוש, קוטל הדרקון, החייל רומאי שקיבל עליו את הנצרות. כנסיית ג\'ורג\' הקדוש המפוארת בעיר העתיקה של לוד, נבנתה מחדש בשנת 1871 על חורבות הכנסייה מימי הביניים, והיא מקום מעניין לביקור. יש לתאם את הביקור מראש בטלפון: 08-922-2023.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1966,
      Vendor_Name: "כנסיית ג'ורג' הקדוש בלוד",
      Product_Url: 'https://info.goisrael.com/he/כנסיית-גורג-הקדוש-בלוד',
      Accessibility: 'לא',
      Address: 'לוד',
      Attraction_Type: 'מקומות קדושים',
      Blue_Flag: '',
      City: 'לוד',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         'יום ראשון: סגור,  יום שני: 10:00 - 17:00, יום שלישי: 10:00 - 17:00, יום רביעי:  10:00 - 17:00, יום חמישי: 10:00 - 17:00, יום שישי: 10:00 - 17:00, יום שבת: 10:00 - 17:00',
      Parking: 'כן',
      Phone: '<a href="tel:+972-8-9222023">+972-8-9222023</a>',
      Region: 'תל אביב והמרכז',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.newyorker.com/magazine/2013/10/21/lydda-1948',
      X: 34.8972506,
      Y: 31.9530402,
   },
   {
      _id: 36,
      Id: 6191,
      Name: 'בית הכנסת הספרדי של האר"י הקדוש',
      ShortDescription:
         'סוג אטרקציה: מקומות קדושים, אזור: צפון, כתובת: רחוב האר"י צפת',
      FullDescription:
         '<p style="direction: rtl;">בית הכנסת הספרדי של האר"י הקדוש הוא בית התפילה העתיק ביותר בצפת.</p>\n<p style="direction: rtl;">בית הכנסת נבנה כמעט 300 שנה לפני שהאר"י (ר\' יצחק לוריא) הגיע לצפת במאה ה-16, ולפי המסורת, האר"י עצמו נהג להתפלל בו. את העיטורים הכחולים שבתוך בית הכנסת מייחסים להשפעת התקופה שבה חיו היהודים בספרד המורית, שם נחשב הצבע הכחול לקדוש.</p>\n<p style="direction: rtl;">בבית הכנסת הבנוי בסגנון יהודי ספרד, יש שתי נקודות מרכזיות: הקיר הדרומי – הקרוב ביותר לירושלים, שבו קבוע ארון הקודש (במקרה זה, שלושה ארונות קודש) והבימה המרכזית המוגבהת.</p>\n<p style="direction: rtl;">צלם: רועי לידמן. File:RoyLindmanAriAshkenaziSynagogue (http://creativecommons.org/licenses/by-sa/3.0),  (http://www.gnu.org/copyleft/fdl.html)  (http://creativecommons.org/licenses/by-sa/3.0)], באמצעות ויקישיתוף.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 432,
      Vendor_Name: 'האר"י הקדוש ',
      Product_Url:
         'https://info.goisrael.com/he/בית-הכנסת-הספרדי-של-הארי-הקדוש',
      Accessibility: 'כן',
      Address: 'רחוב האר"י צפת',
      Attraction_Type: 'מקומות קדושים',
      Blue_Flag: '',
      City: '',
      Diving_beach: '',
      Email: ' <a href="mailto:sacred.haari@gmail.com\t"> sacred.haari@gmail.com\t </a> ',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: 'יש לקבוע הגעה בתיאום מראש',
      Parking: 'כן',
      Phone: ' <a href="tel:+972-50-4898988">+972-50-4898988</a> ',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.safed.co.il/Synagogues/Ari_Sepharadi.html',
      X: 35.4926842,
      Y: 32.968107,
   },
   {
      _id: 37,
      Id: 6192,
      Name: 'בית הכנסת העתיק של פקיעין ',
      ShortDescription:
         'סוג אטרקציה: מקומות קדושים, אתרים לאומיים, אזור: צפון, כתובת: פקיעין העתיקה',
      FullDescription:
         '<p style="direction: rtl;">בית כנסת מ-1873. בקירות המקום משובצות שתי אבנים, שנלקחו לפי המסורת מאבני בית כנסת קדום שנבנה מאבני בית המקדש.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1972,
      Vendor_Name: 'בית הכנסת העתיק של פקיעין ',
      Product_Url: 'https://info.goisrael.com/he/בית-הכנסת-העתיק-של-פקיעין',
      Accessibility: 'כן',
      Address: 'פקיעין העתיקה',
      Attraction_Type: 'אתרים לאומיים;מקומות קדושים',
      Blue_Flag: '',
      City: 'פקיעין (בוקייעה)',
      Diving_beach: '',
      Email: '<a href="mailto:beitzinati@gmail.com">beitzinati@gmail.com</a>',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: 'בתיאום מראש',
      Parking: 'כן',
      Phone: '<a href="tel:+972-4-9571548">+972-4-9571548</a>',
      Region: 'צפון',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'http://www.pekiin.org.il/',
      X: 35.3379837,
      Y: 32.9762125,
   },
   {
      _id: 38,
      Id: 6223,
      Name: 'בית המשפט העליון',
      ShortDescription:
         'סוג אטרקציה: מוזיאונים ותרבות, אזור: ירושלים והסביבה, כתובת: רחוב שערי משפט, ירושלים',
      FullDescription:
         '<p style="direction: rtl;">בית המשפט העליון תוכנן כך שייצור רושם מרשים אבל לא כוחני. המבנה הפך לאתר מבקרים, ויש בו חמישה אולמות משפט מפוארים שאור היום משחק בהם תפקיד חשוב, והנוף נשקף מחלונותיהם הרחבים.</p>\n<p style="direction: rtl;">תמונה מתוך ויקישיתוף - israeltourisem</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1973,
      Vendor_Name: 'בית המשפט העליון',
      Product_Url: 'https://info.goisrael.com/he/בית-המשפט-העליון',
      Accessibility: 'כן',
      Address: 'רחוב שערי משפט, ירושלים',
      Attraction_Type: 'מוזיאונים ותרבות',
      Blue_Flag: '',
      City: 'ירושלים',
      Diving_beach: '',
      Email: '<a href="mailto:marcia@supreme.court.gov.il">marcia@supreme.court.gov.il</a>',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         'יום ראשון: 08:30 - 13:30,  יום שני:  08:30 - 13:30,  יום שלישי:  08:30 - 13:30,  יום רביעי:  08:30 - 13:30, יום חמישי:  08:30 - 13:30, יום ששי: סגור, יום שבת: סגור',
      Parking: 'כן',
      Phone: '<a href="tel:+972-2-6759612">+972-2-6759612</a>',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://www.court.gov.il',
      X: 35.2060211,
      Y: 31.7810317,
   },
   {
      _id: 39,
      Id: 6224,
      Name: 'בית העלמין בהר הזיתים',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: ירושלים והסביבה, כתובת: הר הזיתים, ירושלים.',
      FullDescription:
         '<p style="direction: rtl;">מאז ימי קדם ביקשו יהודים להיקבר בהר הזיתים, שבו תתחיל, לפי המסורת, תחיית המתים. במרוצת הדורות התרחב בית העלמין עד שכיסה חלק גדול מההר.הוא משמש לקבורה גם כיום. <br />אחד הקברים העתיקים ביותר בעמק קדרון הנמצא למרגלות הר הזיתים, מיוחס לאבשלום, בנו המורד של דוד המלך. קבר אחר מיוחס לזכריה הכהן מתקופת בית ראשון; קבר שלישי נושא כתובת המזכירה את בני חֶזיר, משפחת כוהנים מימי בית שני. <br />במרכז המידע של הר הזיתים הנמצא בסמוך ליד אבשלום, יכולים המבקרים לקבל מידע לצורך איתור קברים ספציפיים.</p>\n<p style="direction: rtl;">צלם: אודי שטיינוול.</p>\n<p style="direction: rtl;"> </p>',
      VendorId: 1974,
      Vendor_Name: 'בית העלמין בהר הזיתים',
      Product_Url: 'https://info.goisrael.com/he/בית-העלמין-בהר-הזיתים',
      Accessibility: 'לא',
      Address: 'הר הזיתים, ירושלים.',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: 'ירושלים',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours: '24/7',
      Parking: 'כן',
      Phone: '',
      Region: 'ירושלים והסביבה',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://mountofolives.co.il/he/',
      X: 35.2544531,
      Y: 31.7779492,
   },
   {
      _id: 40,
      Id: 6226,
      Name: 'בית הקברות - רח\' טרומפלדור, ת"א',
      ShortDescription:
         'סוג אטרקציה: ארכיאולוגיה והיסטוריה, אזור: תל אביב והמרכז, כתובת: רח\' טרומפלדור, ת"א',
      FullDescription:
         '<p style="direction: rtl;">בית הקברות הישן ברחוב טרומפלדור בית קברות זה, המצוי בלב העיר, הוקם בשנת 1902 בין דיונות של חול. באתר כ-5000 מצבות, שהסיור ביניהן מהווה דרך ייחודית ללימוד תולדותיה של העיר תל-אביב. <br />כאן טמונים אחדים מהאבות המייסדים של התנועה הציונית וכן דמויות מפתח מעולם התרבות והפוליטיקה התל-אביבית.</p>\n<p style="direction: rtl;">עם אלה נמנים ההוגה אחד העם, ראש העיר הראשון של תל-אביב מאיר דיזנגוף, המשוררים שאול טשרניחובסקי וחיים נחמן ביאליק (ואשתו מניה), הסופרת דבורה ברון והמנהיג הציוני חיים ארלוזורוב.</p>\n<p style="direction: rtl;">גם הסופר והסטיריקן אפרים קישון (1924-2005) קבור כאן.</p>\n<p style="direction: rtl;">צלם: Itaifortis. מתוך אתר פיקיוויקי. </p>\n<p style="direction: rtl;"> </p>',
      VendorId: 2407,
      Vendor_Name: 'מפה',
      Product_Url: 'https://info.goisrael.com/he/בית-הקברות-רח-טרומפלדור-תא',
      Accessibility: 'לא',
      Address: 'רח\' טרומפלדור, ת"א',
      Attraction_Type: 'ארכיאולוגיה והיסטוריה',
      Blue_Flag: '',
      City: 'תל אביב יפו',
      Diving_beach: '',
      Email: '',
      Notes: '',
      Notes_for_opening_hours: '',
      Opening_Hours:
         'יום ראשון: 15:00-06:30,  יום שני: 15:00-06:30 , יום שלישי:  15:00-06:30, יום רביעי:  15:00-06:30, יום חמישי: 15:00-06:30, יום שישי: 13:00-06:30, יום שבת: סגור',
      Parking: 'כן',
      Phone: '',
      Region: 'תל אביב והמרכז',
      Scheduled_visits: '',
      Suitable_for_Children: 'כן',
      Surfing_beach: '',
      URL: 'https://bit.ly/2tzvwha',
      X: 34.772222,
      Y: 32.0756351,
   },
];

export { attractionsData };
